### ISSUE TITLE
Square duplication issue

### ISSUE THREAD

**Issue by elliotchun** [DrPyxel/UniBoardGame#1]
When the player right clicks to roll the die, squares will spawn in and test for collision to make sure the player only moves a certain number of steps. As of now, the squares will stay each time the die is rolled, causing some obvious issues.

**Comment by rabbitsjimmy** [comment]
ok

**Comment by elliotchun** [comment]
Issue resolved. Used a locking system that requires one square and tests for the player to be above a square.
